### ISSUE TITLE
Problems since version of mongodb-odm=1.2.2

### ISSUE THREAD

**Issue by TheHett** [doctrine/DoctrineMongoDBBundle#457]
```
        "doctrine/mongodb-odm": "1.2.2",
        "doctrine/mongodb-odm-bundle": "3.4.2",
```

After update doctrine/mongodb-odm to 1.2.2 there was a problem:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "setRetryConnect" of class "Doctrine\ODM\MongoDB\Configuration". in M:\projects\api\var\cache\dev\ContainerRRNU3Cp\getDoctrineMongodb_Odm_DefaultConfigurationService.php:56
!!  Stack trace:
!!  #0 M:\projects\api\var\cache\dev\ContainerRRNU3Cp\srcDevDebugProjectContainer.php(444): require()
!!  #1 M:\projects\api\var\cache\dev\ContainerRRNU3Cp\getDoctrineMongodb_Odm_DefaultConnectionService.php(10): ContainerRRNU3Cp\srcDevDebugProjectContainer->load('M:\\projects\\hel...')
!!  #2 M:\projects\api\var\cache\dev\ContainerRRNU3Cp\srcDevDebugProjectContainer.php(444): require('M:\\projects\\hel...')
!!  #3 M:\projects\api\var\cache\dev\ContainerRRNU3Cp\getDoctrineMongodb_Odm_DefaultDocumentManagerService.php(12): ContainerRRNU3Cp\srcDevDebugProjectContainer->load('M:\\projects\\hel...')
!!  #4 M:\projects\api\var\cache\dev\Con in M:\projects\api\var\cache\dev\ContainerRRNU3Cp\getDoctrineMongodb_Odm_DefaultConfigurationService.php on line 56

```

**Comment by alcaeus** [comment]
I inadvertently tagged 1.2.2 of `doctrine/mongodb-odm` from the master branch, which is incompatible with the bundle. I now re-tagged the release as 1.2.3 from the correct branch, so an update will solve the problem. My apologies for the inconvenience.

**Comment by TheHett** [comment]
it did not cause problems, thank you!
