### ISSUE TITLE
ClassNotFoundException in 4.0 Beta

### ISSUE THREAD

**Issue by Jan0707** [doctrine/DoctrineMongoDBBundle#525]
I just set up a new installation of Symfony 4.2 and wanted to give this bundle's beta version a chance. My respective composer.json file looks like this (shortened for clarity):

    "require": {
        "php": "^7.3",
        "ext-gd": "*",
        "doctrine/mongodb-odm-bundle": "^4.0@beta",
        "doctrine/mongodb-odm": "^2.0@beta",
        "phpoffice/phpspreadsheet": "^1.6",
        "symfony/console": "^4.2",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.2",
        "symfony/yaml": "^4.2",
        "symfony/var-dumper": "^4.2"
    },
    "require-dev": {
        "symfony/dotenv": "^4.2"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },

During cache warmup however, I encounter the following issue:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AbstractProxyFactory" from namespace "Doctrine\Common\Proxy".
!!  Did you forget a "use" statement for another namespace? in /var/www/html/vendor/doctrine/mongodb-odm-bundle/CacheWarmer/ProxyCacheWarmer.php:59
!!  Stack trace:
!!  #0 /var/www/html/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(96): Doctrine\Bundle\MongoDBBundle\CacheWarmer\ProxyCacheWarmer->warmUp('/var/www/html/v...')
!!  #1 /var/www/html/vendor/symfony/http-kernel/Kernel.php(587): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/var/www/html/v...')
!!  #2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
!!  #3 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #4 /var/www/html/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Componen in /var/www/html/vendor/doctrine/mongodb-odm-bundle/CacheWarmer/ProxyCacheWarmer.php on line 59

```

The class at fault here (/vendor/doctrine/mongodb-odm-bundle/CacheWarmer/ProxyCacheWarmer.php on line 59) does makes the following call:
`if ($this->container->getParameter('doctrine_mongodb.odm.auto_generate_proxy_classes') === AbstractProxyFactory::AUTOGENERATE_EVAL) {`

But the `AbstractProxyFactory` class is non existing.

Is this a known problem, or did I maybe setup something wrongly ? Any input is highly appreciated :) 

Thanks folks!

**Comment by alcaeus** [comment]
This is fixed in master, see #524.

**Comment by Jan0707** [comment]
Thank you :) Will reference `dev-master` for the time being :)
